from __future__ import annotations


pytest_plugins = ["bdd.steps.commands"]


def pytest_bdd_apply_tag(tag: str, function: object) -> bool:
    """Treat .feature tags as opaque spec labels, not pytest markers.

    :param str tag: Gherkin tag from a feature file.
    :param object function: Scenario function generated by pytest-bdd.
    """
    return True
